"""
Reporting layer: generate charts and a markdown summary from the mart tables.

Usage:
    python -m src.pipeline.report --db-path data/warehouse/marketing.duckdb
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

import duckdb
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)-8s | %(message)s")
logger = logging.getLogger(__name__)


def plot_spend_vs_revenue_by_channel(con: duckdb.DuckDBPyConnection, out_path: Path) -> None:
    df = con.execute("""
        SELECT channel, SUM(spend) AS total_spend, SUM(revenue) AS total_revenue
        FROM mart_channel_performance_daily
        WHERE channel IN ('google_ads', 'facebook_ads', 'tiktok_ads', 'linkedin_ads')
        GROUP BY channel ORDER BY channel
        """).df()
    fig, ax = plt.subplots(figsize=(8, 5))
    x = range(len(df))
    width = 0.35
    ax.bar(
        [i - width / 2 for i in x],
        df["total_spend"],
        width,
        label="Spend",
        color="#c0392b",
    )
    ax.bar(
        [i + width / 2 for i in x],
        df["total_revenue"],
        width,
        label="Revenue",
        color="#27ae60",
    )
    ax.set_xticks(list(x))
    ax.set_xticklabels(df["channel"], rotation=20, ha="right")
    ax.set_ylabel("USD")
    ax.set_title("Spend vs. Attributed Revenue by Paid Channel")
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def plot_funnel_conversion(con: duckdb.DuckDBPyConnection, out_path: Path) -> None:
    df = con.execute("SELECT * FROM mart_funnel_conversion ORDER BY page_views DESC").df()
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.bar(
        df["channel"],
        df["page_view_to_signup_rate"] * 100,
        color="#2980b9",
        label="Page view -> Signup",
    )
    ax.bar(
        df["channel"],
        df["signup_to_purchase_rate"] * 100,
        bottom=df["page_view_to_signup_rate"] * 100,
        color="#8e44ad",
        label="Signup -> Purchase",
    )
    ax.set_ylabel("Conversion rate (%)")
    ax.set_title("Funnel Conversion Rates by Channel")
    plt.xticks(rotation=20, ha="right")
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def plot_dq_before_after(staging_summary: dict, mart_summary: dict, out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 4.5))
    labels = ["Staging (raw)", "Marts (cleaned)"]
    passed = [staging_summary["passed"], mart_summary["passed"]]
    total = [staging_summary["total_checks"], mart_summary["total_checks"]]
    failed = [t - p for t, p in zip(total, passed, strict=True)]
    ax.bar(labels, passed, label="Passed", color="#27ae60")
    ax.bar(labels, failed, bottom=passed, label="Failed", color="#c0392b")
    ax.set_ylabel("Number of DQ checks")
    ax.set_title("Data Quality Checks: Before vs. After Cleaning")
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def write_markdown_report(
    con: duckdb.DuckDBPyConnection,
    staging_summary: dict,
    mart_summary: dict,
    out_path: Path,
) -> None:
    cac_df = con.execute("SELECT * FROM mart_customer_acquisition_cost ORDER BY cac").df()
    roas_df = con.execute("""
        SELECT channel, ROUND(SUM(revenue) / NULLIF(SUM(spend), 0), 3) AS overall_roas
        FROM mart_channel_performance_daily
        WHERE channel IN ('google_ads', 'facebook_ads', 'tiktok_ads', 'linkedin_ads')
        GROUP BY channel ORDER BY overall_roas DESC
        """).df()

    lines = [
        "# Marketing Analytics Pipeline Report",
        "",
        "> Auto-generated by `src/pipeline/report.py` from the DuckDB warehouse's mart tables.",
        "",
        "## Data Quality: Before vs. After",
        f"- Staging (raw) checks: **{staging_summary['passed']}/{staging_summary['total_checks']} passed** "
        "(informational only — these issues are expected in raw data)",
        f"- Mart (cleaned) checks: **{mart_summary['passed']}/{mart_summary['total_checks']} passed** "
        "(this is the real gate — the pipeline halts if any of these fail)",
        "",
        "![DQ before/after](../assets/dq_before_after.png)",
        "",
        "## Channel ROAS (Return on Ad Spend)",
        "| Channel | ROAS |",
        "|---|---|",
    ]
    for _, row in roas_df.iterrows():
        lines.append(f"| {row['channel']} | {row['overall_roas']} |")

    lines += [
        "",
        "**Honest finding**: since ad spend and purchase revenue were generated independently in the "
        "synthetic data (not tuned to produce a flattering narrative), ROAS below 1.0 for most channels "
        'here just reflects that — it is not a claim about which channel is realistically "best," only '
        "a demonstration that the pipeline computes the metric correctly end to end.",
        "",
        "## Customer Acquisition Cost by Channel",
        "| Channel | Total Spend | New Customers | CAC |",
        "|---|---|---|---|",
    ]
    for _, row in cac_df.iterrows():
        lines.append(
            f"| {row['channel']} | ${row['total_spend']:,.2f} | {row['new_customers']} | ${row['cac']:,.2f} |"
        )

    lines += [
        "",
        "## Charts",
        "![Spend vs revenue](../assets/spend_vs_revenue.png)",
        "![Funnel conversion](../assets/funnel_conversion.png)",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate charts and report from mart tables")
    parser.add_argument("--db-path", type=str, default="data/warehouse/marketing.duckdb")
    parser.add_argument("--assets-dir", type=str, default="assets")
    parser.add_argument("--docs-dir", type=str, default="docs")
    args = parser.parse_args()

    con = duckdb.connect(args.db_path)
    assets_dir = Path(args.assets_dir)
    docs_dir = Path(args.docs_dir)
    assets_dir.mkdir(parents=True, exist_ok=True)
    docs_dir.mkdir(parents=True, exist_ok=True)

    with open(docs_dir / "dq_report_staging.json") as f:
        staging_summary = json.load(f)
    with open(docs_dir / "dq_report_marts.json") as f:
        mart_summary = json.load(f)

    plot_spend_vs_revenue_by_channel(con, assets_dir / "spend_vs_revenue.png")
    plot_funnel_conversion(con, assets_dir / "funnel_conversion.png")
    plot_dq_before_after(staging_summary, mart_summary, assets_dir / "dq_before_after.png")
    write_markdown_report(con, staging_summary, mart_summary, docs_dir / "pipeline_report.md")

    con.close()
    logger.info("Report generated: %s", docs_dir / "pipeline_report.md")


if __name__ == "__main__":
    main()
